### ISSUE TITLE
Setting stylesheet folder manually

### ISSUE THREAD

**Issue by MisterMakerNL** [Axeia/FreeCAD-Stylesheet-Reloading-Macro#1]
I am working mostly in the roaming folder and the one in the macro is set to the program folder.
Pro of setting the roaming folder is that you can test on different versions.
I changed the stylesheetspath to this:
`stylesheetsPath = "C:/Users/[user]/AppData/Roaming/FreeCAD/Gui/Stylesheets/"`

btw I am very happy with this, done that graph you drawn over 9000 times by now.... 👍

**Comment by Axeia** [comment]
I wasn't aware that stylesheets could reside there and be picked up by FreeCAD.
After some testing it seems like FreeCAD lists files from both folders (user and the program). If they have the same name the user folder file is the one that gets used.
I've changed the code to basically work like this
```mermaid
flowchart TD
    A[Macro checks\n user folder]
    -->B{File Exists?}
    B--Yes-->C[Use user folder\n stylesheet]-->E
    B--No-->D[Use default installation\n folder stylesheet]-->E
    E((Apply \nstylesheet))
```

I've also changed the code a bit to work on theoretically any platform FreeCAD works. Although I'm only able to test Windows and Linux which I can confirm both work.
